# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image_url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('link', models.URLField()),
            ],
        ),
    ]
