# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170201_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddesk',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
